import React, { useEffect, useState } from "react";
import {
  useEngine,
  humanizeAge,
  sendAction,
  checkForUpdates,
  getKeys,
  saveKey,
  rescanNow,
  getAllowlist,
  removeAllowlist,
  validateYara,
  testYara,
  saveYara,
  removeCustomYara,
  listCustomYara,
  uninstallApp,
} from "./api.js";

/* Set VITE_USE_API=false to force the offline demo (mock) data. */
const USE_API =
  !(typeof import.meta !== "undefined" &&
    import.meta.env &&
    import.meta.env.VITE_USE_API === "false");

/* Eyil — a calm, illustrated take on file safety, with a Technical view.
 * Custom hand-drawn SVG (no icon library), soft cool palette, a guardian
 * character that reacts. Toggle between a plain-language story and the raw
 * forensic detail (paths, PIDs, hashes, IPs, event log). */

const P = {
  bg: "#EDEBF6", surface: "#FBFAFF", ink: "#2E2A4F", soft: "#6B6790",
  mint: "#5FBF9B", butter: "#F2C14E", coral: "#F2795B", accent: "#7B6CF6",
  console: "#211E3B", consoleText: "#CFC9EC",
};

const STATE = {
  safe:  { col: P.mint,   word: "Safe" },
  watch: { col: P.butter, word: "Worth a look" },
  risk:  { col: P.coral,  word: "High risk" },
};

const OPCOL = {
  ENCRYPT: P.coral, DELETE: P.coral, WRITE: P.butter,
  READ: P.soft, EXECUTE: P.accent, CONNECT: P.accent,
};
const LVLCOL = { info: P.soft, warn: P.butter, crit: P.coral, ok: P.mint };

function stateWord(f) {
  if (f?.status === "quarantined") return "Stopped";
  return STATE[f?.state || "safe"].word;
}

const MOCK_FILES = [
  {
    id: "f1", name: "report.pdf", state: "safe",
    home: "Lives in your Documents folder",
    uses: "Sips a little power, stays offline",
    opens: ["Itself, to show you the pages"],
    talks: ["Your PDF reader"],
    could: null,
    tech: {
      path: "C:\\Users\\you\\Documents\\report.pdf",
      kind: "Document", pid: "—", parent: "AcroRd32.exe (5120)",
      signer: "n/a", size: "2.4 MB", seen: "2026-06-14 09:12:04",
      sha256: "3f1a9c2e7b4d8051aa6f23c19e0d77b4c8e2f1d09a4b6c33ee71f0a2b5c4d8e9",
      res: { cpu: "0%", mem: "—", disk: "read only" },
      ops: [{ op: "READ", path: "C:\\Users\\you\\Documents\\report.pdf" }],
      net: [],
      services: ["—"],
      logs: [
        { ts: "09:12:04", lvl: "info", msg: "File opened by AcroRd32.exe (pid 5120)" },
        { ts: "09:12:04", lvl: "ok", msg: "Signature scan: clean" },
      ],
    },
  },
  {
    id: "f2", name: "vacation.jpg", state: "safe",
    home: "Lives in your Pictures folder",
    uses: "Barely any power, stays offline",
    opens: ["Itself, when you preview it"],
    talks: ["Photo viewer"],
    could: null,
    tech: {
      path: "C:\\Users\\you\\Pictures\\vacation.jpg",
      kind: "Image", pid: "—", parent: "explorer.exe (3310)",
      signer: "n/a", size: "5.1 MB", seen: "2026-06-13 18:44:51",
      sha256: "b2c4d6e8f0a1b3c5d7e9f1a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2",
      res: { cpu: "0%", mem: "—", disk: "read only" },
      ops: [{ op: "READ", path: "C:\\Users\\you\\Pictures\\vacation.jpg" }],
      net: [],
      services: ["—"],
      logs: [
        { ts: "18:44:51", lvl: "info", msg: "Thumbnail generated by explorer.exe" },
        { ts: "18:44:51", lvl: "ok", msg: "Signature scan: clean" },
      ],
    },
  },
  {
    id: "f3", name: "setup_helper.tmp", state: "watch",
    home: "Lives in a temporary folder",
    uses: "Some power, quietly using the internet",
    opens: ["A few system settings"],
    talks: ["Task scheduler", "A network service"],
    could: "It's unsigned and poking at system settings. Probably fine, but Eyil is keeping an eye on it.",
    tech: {
      path: "C:\\Users\\you\\AppData\\Local\\Temp\\setup_helper.tmp",
      kind: "Executable", pid: "4502", parent: "explorer.exe (3310)",
      signer: "Unsigned", size: "1.8 MB", seen: "2026-06-14 11:39:48",
      sha256: "a91c3f7e2d5b8c40f16a9e3b7d2c5081f4a6e9b0c3d7f2a85e1b4c6d9f0a3e72",
      res: { cpu: "12%", mem: "60 MB", disk: "low" },
      ops: [
        { op: "EXECUTE", path: "C:\\Users\\you\\AppData\\Local\\Temp\\setup_helper.tmp" },
        { op: "READ", path: "C:\\Windows\\System32\\config\\SYSTEM" },
      ],
      net: [
        { dir: "OUT", ip: "52.18.144.3", port: 443, host: "unverified", status: "allowed" },
      ],
      services: [
        { name: "Task Scheduler", action: "registered task \\UpdaterCheck" },
        { name: "Remote Procedure Call", action: "endpoint bound" },
      ],
      logs: [
        { ts: "11:39:48", lvl: "info", msg: "Process started from Temp by explorer.exe" },
        { ts: "11:39:49", lvl: "warn", msg: "Unsigned binary executing from user-writable path" },
        { ts: "11:39:50", lvl: "warn", msg: "Read access to registry hive HKLM\\SYSTEM" },
        { ts: "11:39:51", lvl: "info", msg: "Outbound 52.18.144.3:443 — allowed, monitoring" },
      ],
    },
  },
  {
    id: "f4", name: "invoice_2026.pdf.exe", state: "risk",
    home: "Arrived in your Downloads folder",
    uses: "A lot of power, busy on the internet",
    opens: ["Your documents", "Your photos (312 of them)"],
    talks: ["Backup service", "An unknown server"],
    could: "It pretends to be a PDF, but it was locking up your files and erasing backups. Eyil shut it down before it got far.",
    tech: {
      path: "C:\\Users\\you\\Downloads\\invoice_2026.pdf.exe",
      kind: "Executable", pid: "6691", parent: "explorer.exe (3310)",
      signer: "Unsigned · double extension", size: "4.7 MB", seen: "2026-06-14 11:42:01",
      sha256: "e7b2d8f4a0c6e2b8d4f0a6c2e8b4d0f6a2c8e4b0d6f2a8c4e0b6d2f8a4c0e6b2",
      res: { cpu: "72%", mem: "320 MB", disk: "HIGH write" },
      ops: [
        { op: "ENCRYPT", path: "C:\\Users\\you\\Documents\\taxes.xlsx" },
        { op: "ENCRYPT", path: "C:\\Users\\you\\Documents\\resume.docx" },
        { op: "ENCRYPT", path: "C:\\Users\\you\\Pictures\\*.jpg (312 files)" },
        { op: "WRITE",   path: "C:\\Users\\you\\Desktop\\READ_ME.txt" },
        { op: "DELETE",  path: "Volume Shadow Copies (vssadmin delete shadows)" },
      ],
      net: [
        { dir: "OUT", ip: "185.234.218.7", port: 8080, host: "flagged C2", status: "BLOCKED" },
      ],
      services: [
        { name: "Volume Shadow Copy", action: "deletion attempted — denied" },
        { name: "Network Connections", action: "outbound — blocked" },
      ],
      logs: [
        { ts: "11:42:01", lvl: "info", msg: "Process started from Downloads by explorer.exe" },
        { ts: "11:42:02", lvl: "warn", msg: "Double extension '.pdf.exe' on unsigned binary" },
        { ts: "11:42:04", lvl: "crit", msg: "Rapid write+rename across 40+ files in Documents" },
        { ts: "11:42:05", lvl: "crit", msg: "vssadmin invoked — shadow copy deletion" },
        { ts: "11:42:06", lvl: "crit", msg: "Outbound 185.234.218.7:8080 matches C2 list" },
        { ts: "11:42:07", lvl: "ok",  msg: "Process terminated · file quarantined · network blocked" },
      ],
    },
  },
];

/* ---------- hand-drawn illustrations ---------- */
function Guardian({ mood }) {
  const alert = mood === "alert";
  const ink = P.ink, surf = P.surface;
  // A castellated body: n merlons across x0..x1 (tops at yTop, crenel floor at yFloor),
  // then straight walls down to `bottom`. Returns an SVG path string.
  const fort = (x0, x1, yTop, yFloor, n, bottom) => {
    const seg = 2 * n - 1, w = (x1 - x0) / seg, yAt = (s) => (s % 2 === 0 ? yTop : yFloor);
    let d = `M ${x0} ${yTop}`;
    for (let s = 0; s < seg; s++) {
      const xe = x0 + (s + 1) * w;
      d += ` L ${xe} ${yAt(s)}`;
      if (s < seg - 1) d += ` L ${xe} ${yAt(s + 1)}`;
    }
    return d + ` L ${x1} ${bottom} L ${x0} ${bottom} Z`;
  };
  const flag = alert ? P.coral : P.mint;
  return (
    <svg width="132" height="148" viewBox="0 0 132 148" fill="none">
      <ellipse cx="66" cy="86" rx="62" ry="56" fill={alert ? "#F2795B22" : "#5FBF9B22"} />
      {/* central keep + two flanking towers */}
      <path d={fort(34, 98, 62, 72, 4, 130)} fill={surf} stroke={ink} strokeWidth="3" strokeLinejoin="round" />
      <path d={fort(14, 40, 42, 52, 2, 130)} fill={surf} stroke={ink} strokeWidth="3" strokeLinejoin="round" />
      <path d={fort(92, 118, 42, 52, 2, 130)} fill={surf} stroke={ink} strokeWidth="3" strokeLinejoin="round" />
      {/* arrow-slit windows + pennant flags on the towers */}
      <path d="M27 72 v9 M105 72 v9" stroke={ink} strokeWidth="3" strokeLinecap="round" />
      <path d="M27 42 v-13" stroke={ink} strokeWidth="2.4" strokeLinecap="round" />
      <path d="M27 29 l11 3.5 l-11 3.5 z" fill={flag} stroke={ink} strokeWidth="1.5" strokeLinejoin="round" />
      <path d="M105 42 v-13" stroke={ink} strokeWidth="2.4" strokeLinecap="round" />
      <path d="M105 29 l11 3.5 l-11 3.5 z" fill={flag} stroke={ink} strokeWidth="1.5" strokeLinejoin="round" />
      {/* gate */}
      <path d="M58 130 V114 a8 8 0 0 1 16 0 V130 Z" fill={alert ? "#F2795B1A" : "#5FBF9B1A"} stroke={ink} strokeWidth="2.6" strokeLinejoin="round" />
      {/* cheeks */}
      <circle cx="47" cy="92" r="4.6" fill={alert ? "#F2795B33" : "#FF9A8B44"} />
      <circle cx="85" cy="92" r="4.6" fill={alert ? "#F2795B33" : "#FF9A8B44"} />
      {/* face on the keep */}
      {alert ? (
        <>
          <path d="M43 82 l9 3" stroke={ink} strokeWidth="3" strokeLinecap="round" />
          <path d="M89 82 l-9 3" stroke={ink} strokeWidth="3" strokeLinecap="round" />
          <circle cx="50" cy="89" r="3.2" fill={ink} />
          <circle cx="82" cy="89" r="3.2" fill={ink} />
          <path d="M58 102 Q 66 97, 74 102" stroke={ink} strokeWidth="2.6" strokeLinecap="round" fill="none" />
        </>
      ) : (
        <>
          <circle cx="50" cy="86" r="3.6" fill={ink} />
          <circle cx="82" cy="86" r="3.6" fill={ink} />
          <path d="M57 97 Q 66 104, 75 97" stroke={ink} strokeWidth="2.6" strokeLinecap="round" fill="none" />
        </>
      )}
    </svg>
  );
}
const stk = { stroke: P.ink, strokeWidth: 2.2, fill: "none", strokeLinecap: "round", strokeLinejoin: "round" };
const IcoHome = () => (<svg width="22" height="22" viewBox="0 0 24 24"><path d="M4 10 L12 4 L20 10 V19 a1 1 0 0 1 -1 1 H5 a1 1 0 0 1 -1 -1 Z" {...stk} /><path d="M10 20 v-5 h4 v5" {...stk} /></svg>);
const IcoBolt = () => (<svg width="22" height="22" viewBox="0 0 24 24"><path d="M13 3 L5 13 h6 l-1 8 L19 11 h-6 Z" {...stk} /></svg>);
const IcoPage = () => (<svg width="22" height="22" viewBox="0 0 24 24"><path d="M7 3 h7 l4 4 v14 H7 Z" {...stk} /><path d="M14 3 v4 h4 M9 13 h6 M9 17 h6" {...stk} /></svg>);
const IcoChat = () => (<svg width="22" height="22" viewBox="0 0 24 24"><path d="M4 6 a2 2 0 0 1 2 -2 h12 a2 2 0 0 1 2 2 v8 a2 2 0 0 1 -2 2 H9 l-4 4 v-4 H6 a2 2 0 0 1 -2 -2 Z" {...stk} /></svg>);
const IcoSpark = () => (<svg width="22" height="22" viewBox="0 0 24 24"><path d="M12 3 v18 M3 12 h18 M6 6 l12 12 M18 6 L6 18" {...stk} strokeWidth="1.8" /></svg>);
function FileGlyph({ state }) {
  return (<svg width="34" height="40" viewBox="0 0 34 40">
    <path d="M6 3 h15 l8 8 v26 H6 Z" fill={P.surface} stroke={P.ink} strokeWidth="2.2" strokeLinejoin="round" />
    <path d="M21 3 v8 h8" fill="none" stroke={P.ink} strokeWidth="2.2" strokeLinejoin="round" />
    <circle cx="26" cy="33" r="6" fill={STATE[state].col} stroke={P.surface} strokeWidth="2" />
  </svg>);
}

function Row({ icon, label, children }) {
  return (
    <div style={{ display: "flex", gap: 14, alignItems: "flex-start", padding: "13px 0" }}>
      <div style={{ marginTop: 1, color: P.ink, opacity: 0.85 }}>{icon}</div>
      <div><div style={{ fontSize: 12.5, color: P.soft, marginBottom: 2 }}>{label}</div>
        <div style={{ fontSize: 15, color: P.ink, lineHeight: 1.45 }}>{children}</div></div>
    </div>
  );
}

const mono = { fontFamily: "ui-monospace, 'SF Mono', Menlo, monospace" };

/* ---------- technical view ---------- */
function TechView({ f }) {
  const t = f.tech;
  const Meta = ({ k, v, full }) => (
    <div style={{ minWidth: full ? "100%" : 0 }}>
      <div style={{ fontSize: 11, color: P.soft, marginBottom: 2 }}>{k}</div>
      <div style={{ ...mono, fontSize: 12.5, color: P.ink, wordBreak: "break-all" }}>{v}</div>
    </div>
  );
  return (
    <div>
      {/* path */}
      <div style={{ ...mono, fontSize: 13, color: P.ink, background: P.bg,
        borderRadius: 12, padding: "10px 14px", wordBreak: "break-all", marginBottom: 14 }}>
        {t.path}</div>

      {/* meta grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "12px 18px", marginBottom: 6 }}>
        <Meta k="Type" v={t.kind} />
        <Meta k="PID" v={t.pid} />
        <Meta k="Parent" v={t.parent} />
        <Meta k="Signer" v={t.signer} />
        <Meta k="Size" v={t.size} />
        <Meta k="First seen" v={t.seen} />
      </div>
      <div style={{ marginTop: 6 }}><Meta k="SHA-256" v={t.sha256} full /></div>
      {t.sha256 && t.sha256 !== "—" && (
        <a href={`https://www.virustotal.com/gui/file/${t.sha256}`} target="_blank" rel="noreferrer"
          style={{ display: "inline-block", marginTop: 8, ...mono, fontSize: 12, color: P.accent,
            textDecoration: "none", fontWeight: 600 }}>
          ↗ Look up this hash on VirusTotal.com
        </a>
      )}

      {/* resources */}
      <div style={{ display: "flex", gap: 18, ...mono, fontSize: 12.5, color: P.ink,
        marginTop: 16, paddingTop: 14, borderTop: `1.5px dashed ${P.bg}` }}>
        <span style={{ color: P.soft }}>cpu</span> {t.res.cpu}
        <span style={{ color: P.soft }}>mem</span> {t.res.mem}
        <span style={{ color: P.soft }}>disk</span> {t.res.disk}
      </div>

      {/* file operations */}
      <SectionLabel>File operations</SectionLabel>
      {t.ops.map((o, i) => (
        <div key={i} style={{ display: "flex", gap: 10, alignItems: "center", padding: "5px 0" }}>
          <span style={{ ...mono, fontSize: 10.5, fontWeight: 700, color: "#fff",
            background: OPCOL[o.op] || P.soft, borderRadius: 5, padding: "2px 7px", minWidth: 58, textAlign: "center" }}>
            {o.op}</span>
          <span style={{ ...mono, fontSize: 12.5, color: P.ink, wordBreak: "break-all" }}>{o.path}</span>
        </div>
      ))}

      {/* network */}
      <SectionLabel>Network connections</SectionLabel>
      {t.net.length === 0 ? (
        <div style={{ ...mono, fontSize: 12.5, color: P.soft }}>none observed</div>
      ) : t.net.map((n, i) => (
        <div key={i} style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap", padding: "5px 0", ...mono, fontSize: 12.5 }}>
          <span style={{ color: P.soft }}>{n.dir}</span>
          <span style={{ color: P.ink, fontWeight: 600 }}>{n.ip}:{n.port}</span>
          <span style={{ color: P.soft }}>{n.host}</span>
          <span style={{ color: n.status === "BLOCKED" ? P.coral : P.mint, fontWeight: 700 }}>{n.status}</span>
        </div>
      ))}

      {/* services */}
      <SectionLabel>Services</SectionLabel>
      {t.services.map((s, i) => typeof s === "string" ? (
        <div key={i} style={{ ...mono, fontSize: 12.5, color: P.soft }}>{s}</div>
      ) : (
        <div key={i} style={{ ...mono, fontSize: 12.5, color: P.ink, padding: "3px 0" }}>
          {s.name} <span style={{ color: P.soft }}>— {s.action}</span></div>
      ))}

      {/* event log console */}
      <SectionLabel>Event log</SectionLabel>
      <div style={{ background: P.console, borderRadius: 14, padding: "12px 14px" }}>
        {t.logs.map((l, i) => (
          <div key={i} style={{ ...mono, fontSize: 12, lineHeight: 1.7, display: "flex", gap: 10 }}>
            <span style={{ color: "#7E78A8" }}>{l.ts}</span>
            <span style={{ color: LVLCOL[l.lvl], fontWeight: 700, minWidth: 38 }}>{l.lvl.toUpperCase()}</span>
            <span style={{ color: P.consoleText }}>{l.msg}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
function SectionLabel({ children }) {
  return (<div style={{ fontSize: 11, letterSpacing: 1.2, color: P.soft, fontWeight: 700,
    marginTop: 18, marginBottom: 6, textTransform: "uppercase" }}>{children}</div>);
}

/* ---------- update-health strip (internal notes #5: always visible) ---------- */
function HDot({ col }) {
  return (<span style={{ width: 9, height: 9, borderRadius: "50%", background: col,
    display: "inline-block", marginRight: 7 }} />);
}
function HItem({ col, label, value }) {
  return (
    <span style={{ display: "inline-flex", alignItems: "center" }}>
      <HDot col={col} />
      <span style={{ color: P.soft }}>{label}&nbsp;</span>
      <span style={{ color: P.ink, fontWeight: 600 }}>{value}</span>
    </span>
  );
}
function HealthStrip({ health, connected }) {
  if (!connected) {
    return (
      <div style={{ display: "flex", alignItems: "center", justifyContent: "center",
        fontSize: 12.5, color: P.soft, marginTop: 22 }}>
        <HDot col={P.soft} /> Engine offline — showing demo data
      </div>
    );
  }
  const h = health || {};
  const sigCol = h.signatures_stale ? P.coral : P.mint;
  const feedCol = h.feeds_stale ? P.coral : P.mint;
  const okCol = h.ok ? P.mint : P.butter;
  const clam = h.clam_version && h.clam_version !== "unavailable" && h.clam_version !== "unknown"
    ? h.clam_version : "not running";
  return (
    <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "center", gap: "8px 20px",
      fontSize: 12.5, marginTop: 22, padding: "12px 16px", background: P.surface,
      borderRadius: 16, boxShadow: "0 4px 14px #2E2A4F0F" }}>
      <HItem col={okCol} label="Protection" value={h.ok ? "up to date" : "needs attention"} />
      <HItem col={clam === "not running" ? P.butter : P.mint} label="ClamAV" value={clam} />
      <HItem col={sigCol} label="Signatures"
        value={h.signatures_stale ? `stale · ${humanizeAge(h.signatures_age_seconds)}`
                                  : humanizeAge(h.signatures_age_seconds)} />
      <HItem col={feedCol} label="Threat feed"
        value={h.feeds_stale ? `stale · ${humanizeAge(h.feeds_age_seconds)}`
                             : humanizeAge(h.feeds_age_seconds)} />
      <HItem col={P.accent} label="Blocklist"
        value={`${(h.hash_feed_count ?? 0).toLocaleString()} hashes`} />
      <HItem col={(h.c2_count ?? 0) > 0 ? P.mint : P.soft} label="C2 list"
        value={`${(h.c2_count ?? 0).toLocaleString()} IPs`} />
      <HItem col={(h.yara_rule_count ?? 0) > 0 ? P.mint : P.soft} label="YARA"
        value={`${(h.yara_rule_count ?? 0).toLocaleString()} rules`} />
      <HItem col={h.realtime_active ? P.mint : P.soft} label="Real-time"
        value={h.realtime_active ? "on · user-mode" : "off"} />
      <UpdateNow />
    </div>
  );
}

function UpdateNow() {
  const [busy, setBusy] = useState(false);
  const run = async () => {
    if (busy) return;
    setBusy(true);
    try { await checkForUpdates(); } catch {} finally { setBusy(false); }
  };
  return (
    <button className="pressable" onClick={run} disabled={busy}
      style={{ font: "inherit", fontSize: 12, fontWeight: 700, color: P.accent,
        background: "transparent", border: `1.5px solid ${P.accent}`, borderRadius: 10,
        padding: "4px 12px", cursor: busy ? "default" : "pointer", opacity: busy ? 0.6 : 1 }}>
      {busy ? "Updating…" : "Update now"}</button>
  );
}

function ScanNowButton({ connected }) {
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState(false);
  const run = async () => {
    if (!connected || busy) return;
    setBusy(true); setDone(false);
    try { await rescanNow(); setDone(true); setTimeout(() => setDone(false), 4000); }
    catch {} finally { setBusy(false); }
  };
  return (
    <button className="pressable" onClick={run} disabled={!connected || busy}
      title={connected ? "Scan your watched folders now" : "Connect the engine to scan"}
      style={{ marginTop: 16, font: "inherit", fontSize: 13.5, fontWeight: 700,
        color: connected ? "#fff" : P.soft, background: connected ? P.accent : P.surface,
        border: connected ? "none" : `1.5px solid ${P.bg}`, borderRadius: 14,
        padding: "9px 22px", cursor: connected && !busy ? "pointer" : "default",
        opacity: connected ? 1 : 0.7 }}>
      {busy ? "Scanning your folders…" : done ? "Scan complete ✓" : "Scan my folders now"}</button>
  );
}

function DemoBanner() {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto 16px", background: "#F2C14E22",
      border: `1.5px solid ${P.butter}`, borderRadius: 14, padding: "10px 16px",
      fontSize: 13, color: P.ink, textAlign: "center" }}>
      <b>Demo data.</b> The engine isn’t connected, so these files are illustrative —
      not live detections. Start the engine to see real verdicts.
    </div>
  );
}

/* ---------- BYOK connections (Settings) ---------- */
function KeyRow({ svc, label, hint, st, onSaved }) {
  const [val, setVal] = useState("");
  const [busy, setBusy] = useState(false);
  const set = st && st[svc] && st[svc].set;
  const masked = st && st[svc] && st[svc].masked;
  const save = async (key) => {
    setBusy(true);
    try { await saveKey(svc, key); await onSaved(); setVal(""); }
    catch {} finally { setBusy(false); }
  };
  return (
    <div style={{ padding: "14px 0", borderTop: `1.5px dashed ${P.bg}` }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
        <div style={{ fontSize: 15, fontWeight: 700 }}>{label}</div>
        {set && <span style={{ fontSize: 11, fontWeight: 700, color: "#fff",
          background: P.mint, borderRadius: 8, padding: "2px 8px" }}>connected</span>}
      </div>
      <div style={{ fontSize: 12.5, color: P.soft, margin: "4px 0 10px" }}>{hint}</div>
      {set ? (
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ ...mono, fontSize: 13, color: P.ink }}>{masked}</span>
          <button className="pressable" disabled={busy} onClick={() => save("")}
            style={{ font: "inherit", fontSize: 12.5, fontWeight: 700, color: P.coral,
              background: "transparent", border: `1.5px solid ${P.coral}`, borderRadius: 10,
              padding: "5px 12px", cursor: "pointer" }}>Remove</button>
        </div>
      ) : (
        <div style={{ display: "flex", gap: 8 }}>
          <input type="password" value={val} onChange={(e) => setVal(e.target.value)}
            placeholder="paste key…" style={{ flex: 1, font: "inherit", ...mono, fontSize: 13,
              padding: "8px 12px", border: `1.5px solid ${P.bg}`, borderRadius: 10,
              background: "#fff", color: P.ink }} />
          <button className="pressable" disabled={busy || !val.trim()} onClick={() => save(val.trim())}
            style={{ font: "inherit", fontSize: 13, fontWeight: 700, color: "#fff",
              background: P.accent, border: "none", borderRadius: 10, padding: "8px 16px",
              opacity: (busy || !val.trim()) ? 0.5 : 1, cursor: "pointer" }}>
            {busy ? "Saving…" : "Save"}</button>
        </div>
      )}
    </div>
  );
}

function AllowedList({ items, onChanged }) {
  const [busyKey, setBusyKey] = useState("");
  const remove = async (key) => {
    setBusyKey(key);
    try { await removeAllowlist(key); await onChanged(); }
    catch {} finally { setBusyKey(""); }
  };
  return (
    <div style={{ padding: "14px 0", borderTop: `1.5px dashed ${P.bg}` }}>
      <div style={{ fontSize: 15, fontWeight: 700 }}>Allowed items</div>
      <div style={{ fontSize: 12.5, color: P.soft, margin: "4px 0 10px" }}>
        These are hidden from the dashboard unless they show risky behavior. Remove one to scan and show it again.</div>
      {!items.length ? (
        <div style={{ fontSize: 12.5, color: P.soft }}>No allowed items yet.</div>
      ) : items.map((item) => (
        <div key={item.key} style={{ display: "flex", alignItems: "center", gap: 10,
          padding: "9px 0", borderTop: `1px solid ${P.bg}` }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 13.5, fontWeight: 700, whiteSpace: "nowrap",
              overflow: "hidden", textOverflow: "ellipsis" }}>{item.name || item.key}</div>
            <div style={{ ...mono, fontSize: 11.5, color: P.soft, whiteSpace: "nowrap",
              overflow: "hidden", textOverflow: "ellipsis" }}>{item.path || item.sha256 || item.key}</div>
          </div>
          <button className="pressable" disabled={busyKey === item.key} onClick={() => remove(item.key)}
            style={{ font: "inherit", fontSize: 12.5, fontWeight: 700, color: P.coral,
              background: "transparent", border: `1.5px solid ${P.coral}`, borderRadius: 10,
              padding: "5px 12px", cursor: "pointer", opacity: busyKey === item.key ? 0.5 : 1 }}>
            Remove</button>
        </div>
      ))}
    </div>
  );
}

const EXAMPLE_RULE = `rule My_Suspicious_Marker
{
    meta:
        description = "Flags files containing my custom marker"
    strings:
        $a = "EVIL-MARKER-123" ascii wide nocase
    condition:
        $a
}`;

function CustomRules() {
  const [src, setSrc] = useState(EXAMPLE_RULE);
  const [name, setName] = useState("");
  const [testPath, setTestPath] = useState("");
  const [status, setStatus] = useState(null);   // {kind:'ok'|'err'|'test', text}
  const [items, setItems] = useState([]);
  const [busy, setBusy] = useState(false);

  const loadList = async () => { try { setItems(await listCustomYara()); } catch {} };
  useEffect(() => { loadList(); }, []);

  const run = async (fn) => { setBusy(true); try { await fn(); } finally { setBusy(false); } };
  const doValidate = () => run(async () => {
    try { const r = await validateYara(src);
      setStatus(r.valid ? { kind: "ok", text: `Valid — ${r.rules} rule(s).` }
                        : { kind: "err", text: r.error }); }
    catch { setStatus({ kind: "err", text: "Engine not reachable." }); }
  });
  const doSave = () => run(async () => {
    try { const r = await saveYara(name, src);
      if (r.ok) { setStatus({ kind: "ok", text: `Saved "${r.saved}". Engine now has ${Number(r.total_rules).toLocaleString()} rules.` }); setName(""); await loadList(); }
      else setStatus({ kind: "err", text: r.error }); }
    catch { setStatus({ kind: "err", text: "Save failed." }); }
  });
  const doTest = () => run(async () => {
    try { const r = await testYara(src, testPath);
      if (!r.ok) setStatus({ kind: "err", text: r.error });
      else setStatus({ kind: "test", text: r.matched ? `MATCH → ${r.rules.join(", ")}` : "No match on that file." }); }
    catch { setStatus({ kind: "err", text: "Test failed." }); }
  });
  const doRemove = (n) => run(async () => { try { await removeCustomYara(n); await loadList(); } catch {} });

  const sc = status?.kind === "ok" ? P.mint : status?.kind === "err" ? P.coral : P.accent;
  const ghost = { font: "inherit", fontSize: 12.5, fontWeight: 700, color: P.accent,
    background: "transparent", border: `1.5px solid ${P.accent}`, borderRadius: 10, padding: "7px 14px", cursor: "pointer" };
  const primary = { font: "inherit", fontSize: 12.5, fontWeight: 700, color: "#fff",
    background: P.accent, border: "none", borderRadius: 10, padding: "7px 16px", cursor: "pointer" };
  const inp = { font: "inherit", ...mono, fontSize: 12.5, padding: "7px 10px",
    border: `1.5px solid ${P.bg}`, borderRadius: 10, background: "#fff", color: P.ink };

  return (
    <div style={{ padding: "14px 0", borderTop: `1.5px dashed ${P.bg}` }}>
      <div style={{ fontSize: 15, fontWeight: 700 }}>Your YARA rules</div>
      <div style={{ fontSize: 12.5, color: P.soft, margin: "4px 0 10px" }}>
        Write your own detection rule — Eyil compiles it straight into the engine. This is
        your AV; teach it what to look for.</div>
      <textarea value={src} onChange={(e) => setSrc(e.target.value)} spellCheck={false}
        style={{ width: "100%", height: 150, boxSizing: "border-box", ...mono, fontSize: 12,
          padding: "10px 12px", border: `1.5px solid ${P.bg}`, borderRadius: 12,
          background: "#fff", color: P.ink, resize: "vertical" }} />
      <div style={{ display: "flex", gap: 8, marginTop: 8, flexWrap: "wrap", alignItems: "center" }}>
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder="file name (e.g. my_rules)"
          style={{ ...inp, flex: 1, minWidth: 130 }} />
        <button className="pressable" disabled={busy} onClick={doValidate} style={ghost}>Validate</button>
        <button className="pressable" disabled={busy} onClick={doSave} style={primary}>Save</button>
      </div>
      <div style={{ display: "flex", gap: 8, marginTop: 8, alignItems: "center" }}>
        <input value={testPath} onChange={(e) => setTestPath(e.target.value)} placeholder="test against a file path…"
          style={{ ...inp, flex: 1 }} />
        <button className="pressable" disabled={busy} onClick={doTest} style={ghost}>Test</button>
      </div>
      {status && (
        <div style={{ ...mono, fontSize: 12, color: sc, marginTop: 8, wordBreak: "break-word",
          background: P.bg, borderRadius: 8, padding: "8px 10px" }}>{status.text}</div>
      )}
      {!!items.length && (
        <div style={{ marginTop: 10 }}>
          {items.map((it) => (
            <div key={it.name} style={{ display: "flex", alignItems: "center", gap: 10,
              padding: "7px 0", borderTop: `1px solid ${P.bg}` }}>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ ...mono, fontSize: 12.5, fontWeight: 700 }}>{it.name}</div>
                <div style={{ fontSize: 11.5, color: P.soft, whiteSpace: "nowrap",
                  overflow: "hidden", textOverflow: "ellipsis" }}>{(it.rules || []).join(", ") || "—"}</div>
              </div>
              <button className="pressable" disabled={busy} onClick={() => doRemove(it.name)}
                style={{ font: "inherit", fontSize: 12, fontWeight: 700, color: P.coral, background: "transparent",
                  border: `1.5px solid ${P.coral}`, borderRadius: 10, padding: "4px 11px", cursor: "pointer" }}>Remove</button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/* Danger zone: remove Eyil Guard from this machine (autostart + shortcut + logs,
   then the listener stops). Two-step confirm so it can't be hit by accident. */
function DangerZone() {
  const [armed, setArmed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState(false);
  const [err, setErr] = useState("");
  const doUninstall = async () => {
    setBusy(true); setErr("");
    try { await uninstallApp(); setDone(true); }
    catch { setErr("Couldn't reach the engine. Run uninstall.ps1 instead."); setBusy(false); }
  };
  const box = { padding: "14px 0 2px", borderTop: `1.5px dashed ${P.bg}` };
  if (done) return (
    <div style={box}>
      <div style={{ fontSize: 15, fontWeight: 700, color: P.mint }}>Eyil Guard removed</div>
      <div style={{ fontSize: 12.5, color: P.soft, marginTop: 4 }}>
        Autostart, the desktop shortcut and the logs are gone, and the listener is stopping.
        You can close this window now. To delete the program files too, remove the project folder.</div>
    </div>
  );
  return (
    <div style={box}>
      <div style={{ fontSize: 15, fontWeight: 700, color: P.coral }}>Remove Eyil Guard</div>
      <div style={{ fontSize: 12.5, color: P.soft, marginTop: 4 }}>
        Stops the background listener and removes the autostart entry, the desktop shortcut and the
        logs. Your project folder and ClamAV are left alone. This closes Eyil.</div>
      {err && <div style={{ fontSize: 12.5, color: P.coral, marginTop: 6 }}>{err}</div>}
      {!armed ? (
        <button className="pressable" onClick={() => setArmed(true)}
          style={{ marginTop: 10, font: "inherit", fontWeight: 700, fontSize: 13.5, color: P.coral,
            background: "transparent", border: `1.5px solid ${P.coral}`, borderRadius: 12,
            padding: "8px 16px", cursor: "pointer" }}>Remove Eyil Guard…</button>
      ) : (
        <div style={{ display: "flex", gap: 10, marginTop: 10, alignItems: "center", flexWrap: "wrap" }}>
          <span style={{ fontSize: 13, fontWeight: 700 }}>Are you sure?</span>
          <button className="pressable" disabled={busy} onClick={doUninstall}
            style={{ font: "inherit", fontWeight: 700, fontSize: 13.5, color: "#fff", background: P.coral,
              border: "none", borderRadius: 12, padding: "8px 16px", cursor: "pointer", opacity: busy ? 0.6 : 1 }}>
            {busy ? "Removing…" : "Yes, remove everything"}</button>
          <button className="pressable" disabled={busy} onClick={() => setArmed(false)}
            style={{ font: "inherit", fontWeight: 700, fontSize: 13.5, color: P.soft, background: "transparent",
              border: `1.5px solid ${P.bg}`, borderRadius: 12, padding: "8px 16px", cursor: "pointer" }}>
            Cancel</button>
        </div>
      )}
    </div>
  );
}

function SettingsModal({ onClose }) {
  const [st, setSt] = useState(null);
  const [allowed, setAllowed] = useState([]);
  const load = async () => {
    try {
      const [keys, allowlist] = await Promise.all([getKeys(), getAllowlist()]);
      setSt(keys);
      setAllowed(allowlist);
    } catch {
      setSt({});
      setAllowed([]);
    }
  };
  useEffect(() => { load(); }, []);
  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "#2E2A4F66",
      display: "flex", alignItems: "flex-start", justifyContent: "center",
      padding: "56px 18px", zIndex: 50, overflowY: "auto" }}>
      <div onClick={(e) => e.stopPropagation()} style={{ background: P.surface, borderRadius: 24,
        padding: "22px 26px", maxWidth: 520, width: "100%", boxShadow: "0 20px 60px #2E2A4F33" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ fontSize: 20, fontWeight: 700 }}>Connections</div>
          <button className="pressable" onClick={onClose} style={{ font: "inherit", fontSize: 22,
            lineHeight: 1, color: P.soft, background: "transparent", border: "none", cursor: "pointer" }}>×</button>
        </div>
        <p style={{ fontSize: 13, color: P.soft, margin: "6px 0 2px" }}>
          Add your own free API keys to unlock more protection. Keys are stored only on this
          computer (<span style={{ ...mono }}>data/keys.json</span>) and are never shared or uploaded.</p>
        <KeyRow svc="abuse_ch" label="abuse.ch" st={st} onSaved={load}
          hint="Unlocks ThreatFox + URLhaus — more malware hashes & botnet C2 IPs. Free key at auth.abuse.ch." />
        <KeyRow svc="malpedia" label="Malpedia" st={st} onSaved={load}
          hint="Pulls Malpedia's curated YARA rules (incl. TLP:GREEN/AMBER) to this machine only — never bundled. Free key at malpedia.caad.fkie.fraunhofer.de." />
        <AllowedList items={allowed} onChanged={load} />
        <CustomRules />
        <div style={{ padding: "14px 0 2px", borderTop: `1.5px dashed ${P.bg}` }}>
          <div style={{ fontSize: 15, fontWeight: 700 }}>VirusTotal</div>
          <div style={{ fontSize: 12.5, color: P.soft, marginTop: 4 }}>
            No key field — VirusTotal's terms forbid using its API inside an antivirus. Instead,
            open any file's <b>Technical</b> view and click <b>“Look up on VirusTotal.com”</b> to
            check it manually in your browser.</div>
        </div>
        <DangerZone />
      </div>
    </div>
  );
}

/* Small app-icon fortress for the header (a flat, face-less version of the mascot). */
function Logo({ size = 32 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-label="Eyil Guard">
      <rect x="1.5" y="1.5" width="29" height="29" rx="8" fill={P.accent} />
      <path d="M7 24 V14 h2.4 v-3 h2.4 v3 h2.4 v-3 h2.4 v3 h2.4 v-3 h2.4 v3 H25 V24 Z" fill="#fff" />
      <rect x="13.6" y="18.5" width="4.8" height="5.5" rx="1.4" fill={P.accent} />
    </svg>
  );
}

/* The live process inventory: everything running, all safe. Collapsed by default so
   the home stays calm — but one click reveals the full list (the transparency promise). */
function RunningApps({ apps, selId, onPick }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ background: P.surface, borderRadius: 20, boxShadow: "0 4px 14px #2E2A4F0F",
      marginBottom: 18, overflow: "hidden" }}>
      <button className="pressable" onClick={() => setOpen(!open)}
        style={{ width: "100%", display: "flex", alignItems: "center", gap: 10, font: "inherit",
          background: "transparent", border: "none", padding: "14px 18px", cursor: "pointer",
          color: P.ink, textAlign: "left" }}>
        <span style={{ width: 9, height: 9, borderRadius: 9, background: P.mint, flex: "0 0 auto" }} />
        <span style={{ fontWeight: 700, fontSize: 14.5 }}>Running apps</span>
        <span style={{ fontSize: 13, color: P.soft }}>{apps.length} watched · all safe</span>
        <span style={{ marginLeft: "auto", color: P.soft, fontSize: 18, lineHeight: 1,
          transform: open ? "rotate(90deg)" : "none", transition: "transform .15s" }}>›</span>
      </button>
      {open && (
        <div style={{ borderTop: `1.5px solid ${P.bg}`, maxHeight: 300, overflowY: "auto" }}>
          {apps.map((f) => (
            <div key={f.id} className="pressable" onClick={() => onPick(f.id)}
              style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 18px",
                borderTop: `1px solid ${P.bg}`, background: f.id === selId ? P.bg : "transparent" }}>
              <span style={{ width: 7, height: 7, borderRadius: 7, background: P.mint, flex: "0 0 auto" }} />
              <span style={{ fontSize: 13.5, fontWeight: 600, flex: 1, whiteSpace: "nowrap",
                overflow: "hidden", textOverflow: "ellipsis" }}>{f.name}</span>
              <span style={{ fontSize: 12, color: P.soft }}>Safe ›</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/* Native window controls for the frameless desktop window (no-ops in a browser). */
const nativeWin = () =>
  (typeof window !== "undefined" && window.pywebview && window.pywebview.api) || null;
const MinIcon = () => (<svg width="11" height="11" viewBox="0 0 11 11"><line x1="1" y1="6" x2="10" y2="6" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" /></svg>);
const MaxIcon = () => (<svg width="11" height="11" viewBox="0 0 11 11"><rect x="1.4" y="1.4" width="8.2" height="8.2" rx="1.8" fill="none" stroke="currentColor" strokeWidth="1.4" /></svg>);
const CloseIcon = () => (<svg width="11" height="11" viewBox="0 0 11 11"><path d="M1.6 1.6 L9.4 9.4 M9.4 1.6 L1.6 9.4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg>);

/* The app's own title bar: brand on the left (drag region), settings + window
   controls on the right. Replaces the OS window chrome (the window is frameless). */
function TitleBar({ onSettings }) {
  const ctl = (fn) => () => { const a = nativeWin(); if (a && a[fn]) a[fn](); };
  const btn = { width: 46, height: 44, border: "none", background: "transparent",
    cursor: "pointer", color: P.soft, display: "grid", placeItems: "center", font: "inherit" };
  return (
    <div style={{ flex: "0 0 auto", height: 44, display: "flex", alignItems: "stretch",
      background: P.surface, borderBottom: `1px solid ${P.bg}`, userSelect: "none" }}>
      <div className="pywebview-drag-region" style={{ flex: 1, display: "flex", alignItems: "center",
        gap: 9, padding: "0 14px", minWidth: 0 }}>
        <Logo size={22} />
        <span style={{ fontWeight: 800, fontSize: 14, letterSpacing: -0.2 }}>Eyil Guard</span>
        <span style={{ fontSize: 11.5, color: P.soft, whiteSpace: "nowrap", overflow: "hidden",
          textOverflow: "ellipsis" }}>· watching quietly</span>
      </div>
      <button className="winbtn" onClick={onSettings} title="Settings"
        style={{ ...btn, fontSize: 16 }}>⚙</button>
      <button className="winbtn" onClick={ctl("minimize")} title="Minimize" style={btn}><MinIcon /></button>
      <button className="winbtn" onClick={ctl("toggle_maximize")} title="Maximize" style={btn}><MaxIcon /></button>
      <button className="winbtn winbtn-close" onClick={ctl("close")} title="Close" style={btn}><CloseIcon /></button>
    </div>
  );
}

export default function App() {
  const [settings, setSettings] = useState(false);
  const { files: liveFiles, health, connected } = useEngine(USE_API);
  const usingDemo = !connected;                       // never show mock unlabelled
  const files = connected ? liveFiles : MOCK_FILES;
  const [selId, setSelId] = useState(null);
  const [view, setView] = useState("simple");

  // keep the selection valid as the live list changes
  useEffect(() => {
    if (!files.length) { if (selId !== null) setSelId(null); return; }
    if (files.find((f) => f.id === selId)) return;            // keep a valid selection
    const firstThreat = files.find((f) => f.state !== "safe");
    setSelId(firstThreat ? firstThreat.id : null);            // default to a threat, else none
  }, [files, selId]);

  const sel = files.find((f) => f.id === selId) || null;
  const anyRisk = files.some((f) => f.state === "risk");
  const threats = files.filter((f) => f.state !== "safe");    // risk + watch
  const safeApps = files.filter((f) => f.state === "safe");   // the calm running inventory

  // Action buttons act only against the live engine; in demo mode they're disabled.
  const canAct = connected && sel && sel.pid != null;
  const [busy, setBusy] = useState(false);
  const onAction = async (action) => {
    if (!canAct || busy) return;
    setBusy(true);
    try {
      await sendAction(sel.pid, action); // engine broadcasts -> hook re-fetches
    } catch {
      /* transient; the next /objects refresh will reconcile */
    } finally {
      setBusy(false);
    }
  };

  return (
    <div style={{ background: P.bg, height: "100vh", overflow: "hidden", display: "flex",
      flexDirection: "column", fontFamily: "ui-rounded, 'SF Pro Rounded', system-ui, sans-serif", color: P.ink }}>
      <style>{`
        @keyframes floaty { 0%,100%{ transform: translateY(0) } 50%{ transform: translateY(-7px) } }
        .float { animation: floaty 4s ease-in-out infinite; }
        .card { cursor:pointer; transition: transform .15s ease; }
        .card:hover { transform: translateY(-3px); }
        .pressable { cursor:pointer; transition: transform .12s ease; }
        .pressable:active { transform: scale(.97); }
        .winbtn { transition: background .12s ease, color .12s ease; }
        .winbtn:hover { background: ${P.bg}; color: ${P.ink}; }
        .winbtn-close:hover { background: ${P.coral}; color: #fff; }
        .scroll::-webkit-scrollbar { width: 10px; }
        .scroll::-webkit-scrollbar-thumb { background: #2E2A4F22; border-radius: 8px; }
        @media (prefers-reduced-motion: reduce){ .float{ animation:none } }
      `}</style>

      {settings && <SettingsModal onClose={() => setSettings(false)} />}

      <TitleBar onSettings={() => setSettings(true)} />
      {usingDemo && <DemoBanner />}

      <div className="scroll" style={{ flex: 1, minHeight: 0, overflowY: "auto", padding: "24px 22px 28px" }}>
      <div style={{ maxWidth: 760, margin: "0 auto" }}>
        {/* hero */}
        <div style={{ textAlign: "center", marginBottom: 16 }}>
          <div className="float" style={{ display: "inline-block" }}>
            <Guardian mood={anyRisk ? "alert" : "calm"} />
          </div>
          <h1 style={{ fontSize: 26, fontWeight: 700, margin: "4px 0 3px", letterSpacing: -0.5 }}>
            {anyRisk ? "One thing needed me." : "Everything's calm."}</h1>
          <p style={{ fontSize: 15, color: P.soft, margin: 0 }}>
            {anyRisk ? "I stopped something and tucked it away. Here's what happened."
                     : threats.length ? "A couple of things are worth a glance — nothing urgent."
                     : "I'm watching everything that runs. Nothing needs you right now."}</p>
          <ScanNowButton connected={connected} />
        </div>

        {/* threats first — only things that actually need attention get a card */}
        {threats.length > 0 && (
          <div style={{ display: "flex", gap: 12, overflowX: "auto", paddingBottom: 6, marginBottom: 18 }}>
            {threats.map((f) => {
              const on = f.id === selId;
              return (
                <div key={f.id} className="card" onClick={() => setSelId(f.id)}
                  style={{ flex: "0 0 auto", width: 150, background: P.surface, borderRadius: 20, padding: 16,
                    border: `2px solid ${on ? STATE[f.state].col : "transparent"}`,
                    boxShadow: on ? "0 8px 22px #2E2A4F1A" : "0 4px 14px #2E2A4F0F" }}>
                  <FileGlyph state={f.state} />
                  <div style={{ fontSize: 14, fontWeight: 600, marginTop: 10, whiteSpace: "nowrap",
                    overflow: "hidden", textOverflow: "ellipsis" }}>{f.name}</div>
                  <div style={{ fontSize: 12.5, color: STATE[f.state].col, fontWeight: 600, marginTop: 2 }}>
                    {stateWord(f)}</div>
                </div>
              );
            })}
          </div>
        )}

        {/* everything else that's running, all safe — collapsed so it never clutters */}
        {safeApps.length > 0 && (
          <RunningApps apps={safeApps} selId={selId} onPick={setSelId} />
        )}

        {/* the engine has genuinely seen nothing yet */}
        {files.length === 0 && (
          <div style={{ textAlign: "center", color: P.soft, fontSize: 14.5, background: P.surface,
            borderRadius: 24, padding: "40px 24px", marginBottom: 18, boxShadow: "0 4px 14px #2E2A4F0F" }}>
            Nothing has happened yet. Eyil is watching — files appear here as they’re opened or scanned.
          </div>
        )}

        {sel && (
          <>
            {/* view toggle */}
            <div style={{ display: "flex", justifyContent: "center", marginBottom: 18 }}>
              <div style={{ display: "inline-flex", background: P.surface, borderRadius: 14, padding: 4,
                boxShadow: "0 4px 14px #2E2A4F0F" }}>
                {[["simple", "Simple"], ["technical", "Technical"]].map(([v, label]) => (
                  <button key={v} className="pressable" onClick={() => setView(v)}
                    style={{ font: "inherit", fontWeight: 700, fontSize: 13.5, border: "none",
                      borderRadius: 11, padding: "8px 22px", cursor: "pointer",
                      background: view === v ? P.accent : "transparent",
                      color: view === v ? "#fff" : P.soft }}>{label}</button>
                ))}
              </div>
            </div>

            {/* story / detail */}
            <div style={{ background: P.surface, borderRadius: 28, padding: "26px 30px", boxShadow: "0 10px 30px #2E2A4F12" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: view === "simple" ? 4 : 16 }}>
                <FileGlyph state={sel.state} />
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 19, fontWeight: 700 }}>{sel.name}</div>
                  <div style={{ fontSize: 14, color: STATE[sel.state].col, fontWeight: 600 }}>{stateWord(sel)}</div>
                </div>
                {sel.status !== "active" && (
                  <span style={{ fontSize: 12, fontWeight: 700, color: "#fff",
                    background: (sel.status === "quarantined" || (sel.status === "allowed" && sel.state !== "safe")) ? P.coral : P.mint,
                    borderRadius: 10, padding: "5px 11px" }}>
                    {sel.status === "quarantined" ? "Quarantined"
                      : sel.state !== "safe" ? "Allowed · flagged again" : "Allowed by you"}</span>
                )}
              </div>

              {view === "simple" ? (
                <div style={{ borderTop: `1.5px dashed ${P.bg}`, marginTop: 14 }}>
                  <Row icon={<IcoHome />} label="Where it lives">{sel.home}</Row>
                  <div style={{ borderTop: `1.5px dashed ${P.bg}` }} />
                  <Row icon={<IcoBolt />} label="Internet use">{sel.uses}</Row>
                  <div style={{ borderTop: `1.5px dashed ${P.bg}` }} />
                  <Row icon={<IcoPage />} label="Files it touches">{sel.opens.join(", ")}</Row>
                  <div style={{ borderTop: `1.5px dashed ${P.bg}` }} />
                  <Row icon={<IcoChat />} label="Network connections">{sel.talks.join(", ")}</Row>
                  <div style={{ borderTop: `1.5px dashed ${P.bg}` }} />
                  <Row icon={<IcoSpark />} label={sel.state === "safe" ? "Anything to worry about?" : "What it could do"}>
                    {sel.could || "Nothing unusual. This one's behaving exactly as expected."}</Row>
                </div>
              ) : (
                <TechView f={sel} />
              )}

              {sel.status === "quarantined" ? (
                <div style={{ display: "flex", gap: 12, marginTop: 22, alignItems: "center", flexWrap: "wrap" }}>
                  <span style={{ fontSize: 13.5, color: P.soft }}>Tucked away. You can let it back if this was a mistake.</span>
                  <button className="pressable" disabled={!canAct || busy} onClick={() => onAction("allow")}
                    style={{ font: "inherit", fontWeight: 700, fontSize: 15, color: P.ink, background: "transparent",
                      border: `2px solid ${P.bg}`, borderRadius: 16, padding: "13px 24px",
                      opacity: canAct && !busy ? 1 : 0.5, cursor: canAct && !busy ? "pointer" : "not-allowed" }}>
                    Restore &amp; allow</button>
                </div>
              ) : sel.status === "allowed" ? (
                <div style={{ display: "flex", gap: 12, marginTop: 22, alignItems: "center", flexWrap: "wrap" }}>
                  <span style={{ fontSize: 13.5, color: P.soft, flexBasis: "100%" }}>
                    You're allowing this. Eyil keeps watching it and will re-alert if it does something harmful.</span>
                  {sel.state !== "safe" && (
                    <button className="pressable" disabled={!canAct || busy} onClick={() => onAction("quarantine")}
                      style={{ font: "inherit", fontWeight: 700, fontSize: 15, color: P.surface,
                        background: P.coral, border: "none", borderRadius: 16, padding: "13px 24px",
                        opacity: canAct && !busy ? 1 : 0.5, cursor: canAct && !busy ? "pointer" : "not-allowed" }}>
                      Quarantine it</button>
                  )}
                  <button className="pressable" disabled={!canAct || busy} onClick={() => onAction("unallow")}
                    style={{ font: "inherit", fontWeight: 700, fontSize: 15, color: P.ink,
                      background: "transparent", border: `2px solid ${P.bg}`, borderRadius: 16, padding: "13px 24px",
                      opacity: canAct && !busy ? 1 : 0.5, cursor: canAct && !busy ? "pointer" : "not-allowed" }}>
                    Stop allowing</button>
                </div>
              ) : sel.state !== "safe" ? (
                <div style={{ display: "flex", gap: 12, marginTop: 22, alignItems: "center", flexWrap: "wrap" }}>
                  <button className="pressable" disabled={!canAct || busy} onClick={() => onAction("quarantine")}
                    style={{ font: "inherit", fontWeight: 700, fontSize: 15, color: P.surface,
                      background: sel.state === "risk" ? P.coral : P.accent, border: "none", borderRadius: 16, padding: "13px 24px",
                      opacity: canAct && !busy ? 1 : 0.5, cursor: canAct && !busy ? "pointer" : "not-allowed" }}>
                    {sel.state === "risk" ? "Keep it out" : "Quarantine"}</button>
                  <button className="pressable" disabled={!canAct || busy} onClick={() => onAction("allow")}
                    style={{ font: "inherit", fontWeight: 700, fontSize: 15, color: P.ink,
                      background: "transparent", border: `2px solid ${P.bg}`, borderRadius: 16, padding: "13px 24px",
                      opacity: canAct && !busy ? 1 : 0.5, cursor: canAct && !busy ? "pointer" : "not-allowed" }}>
                    It's fine, allow it</button>
                  {!connected && (
                    <span style={{ fontSize: 12.5, color: P.soft }}>Connect the engine to take action</span>
                  )}
                </div>
              ) : null}
            </div>
          </>
        )}

        <HealthStrip health={health} connected={connected} />
      </div>
      </div>
    </div>
  );
}
